#!/usr/bin/env python3
"""Regenerate the web + mobile lookup tables for catalog agent icons.

The marks themselves are plain files (`apps/web/public/images/acp/<id>.svg`,
`apps/mobile/assets/images/acp/<id>.svg`); this only emits the *index* the
clients need — which ids have a mark, and what a session's display name maps
back to. Both are derived from `protocol.acp_catalog`, so the index can never
drift from the catalog the backend serves.

Why an index at all: a client renders an agent from whatever string it has,
which is the provider id in the picker (`cline`) but the display *label* on a
running session (`Cline`, `Factory Droid`). Both have to find the same file,
and a miss must be detectable so the caller can fall back to the generated
initial-square rather than draw nothing.

    python backend/scripts/gen_acp_icons.py         # rewrite both files
    python backend/scripts/gen_acp_icons.py --check # CI: fail if stale

Run it after adding a catalog entry or dropping in a new SVG. The icon only
reaches users with the next web deploy / app release — deliberately: a catalog
entry works the moment the backend has it, the mark is cosmetic and degrades
to the initial-square.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
WEB_ICONS = REPO / "apps/web/public/images/acp"
MOBILE_ICONS = REPO / "apps/mobile/assets/images/acp"
WEB_OUT = REPO / "apps/web/lib/acp-provider-icons.ts"
MOBILE_OUT = REPO / "apps/mobile/lib/backend/acp_provider_icons.dart"

#: Agents Vicoa ships with hand-tuned brand marks in `AGENT_LOGOS` /
#: `_AGENT_LOGOS`. A generated key must never shadow one of these: the
#: generated map is consulted first, and it has no light/dark treatment.
RESERVED = {
    "claude",
    "claude code",
    "codex",
    "opencode",
    "cursor",
    "gemini",
    "gemini cli",
    "copilot",
    "copilot cli",
    "kimi",
    "kimi cli",
    "hermes",
    "pi",
    "omp",
    "oh my pi",
}

BANNED = re.compile(
    r"<script|\son\w+\s*=|javascript:|<foreignObject|(?:xlink:)?href\s*=\s*[\"']\s*(?:https?:)?//",
    re.IGNORECASE,
)


def slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")


def build_index() -> dict[str, str]:
    """`{lookup key: icon basename}` for every catalog entry that has a mark."""
    sys.path.insert(0, str(REPO / "backend/src"))
    from protocol.acp_catalog import ACP_CATALOG

    available = {p.stem for p in WEB_ICONS.glob("*.svg")}
    mobile_available = {p.stem for p in MOBILE_ICONS.glob("*.svg")}
    if available != mobile_available:
        raise SystemExit(
            f"web and mobile icon sets differ: only web {sorted(available - mobile_available)}, "
            f"only mobile {sorted(mobile_available - available)}"
        )

    index: dict[str, str] = {}
    for entry in ACP_CATALOG:
        icon = entry["id"]
        if icon not in available:
            continue
        svg = (WEB_ICONS / f"{icon}.svg").read_text(encoding="utf-8")
        if BANNED.search(svg):
            raise SystemExit(f"{icon}.svg contains script, a handler or a remote reference")
        # The id, plus what a running session is labelled with. Both land here.
        for key in {entry["id"], entry["label"].lower(), slug(entry["label"])}:
            if not key or key in RESERVED:
                continue
            if index.get(key, icon) != icon:
                raise SystemExit(f"icon key {key!r} claimed by both {index[key]} and {icon}")
            index[key] = icon

    orphans = available - {e["id"] for e in ACP_CATALOG}
    if orphans:
        raise SystemExit(f"icons with no catalog entry: {sorted(orphans)}")
    return dict(sorted(index.items()))


HEADER = """Generated by backend/scripts/gen_acp_icons.py — do not edit by hand.

Maps a provider id, or the display name a running session carries, to its
brand mark under {icons}. A key that is absent has no mark; the caller
draws the generated initial-square rather than nothing."""


def comment(prefix: str, icons: str) -> str:
    """Prefix each header line, leaving no trailing whitespace on blank ones."""
    lines = HEADER.format(icons=icons).split("\n")
    return "\n".join((prefix + line).rstrip() for line in lines)


def render_ts(index: dict[str, str]) -> str:
    body = "\n".join(f"  '{key}': '{icon}'," for key, icon in index.items())
    return (
        "/**\n"
        + comment(" * ", "public/images/acp/")
        + "\n */\n\n"
        + "const ACP_ICON_BY_KEY: Record<string, string> = {\n"
        + body
        + "\n};\n\n"
        + "/** Public path of the mark for `key`, or null when there is none. */\n"
        + "export function acpIconSrc(key: string | null | undefined): string | null {\n"
        + "  if (!key) return null;\n"
        + "  const icon = ACP_ICON_BY_KEY[key.trim().toLowerCase()];\n"
        + "  return icon ? `/images/acp/${icon}.svg` : null;\n"
        + "}\n\n"
        + "/** Every lookup key that resolves to a mark. Exported for tests. */\n"
        + "export const ACP_ICON_KEYS = Object.keys(ACP_ICON_BY_KEY);\n"
    )


def render_dart(index: dict[str, str]) -> str:
    body = "\n".join(f"  '{key}': '{icon}'," for key, icon in index.items())
    return (
        # Plain `//`, not `///`: a doc comment with no declaration under it
        # trips the analyzer's dangling_library_doc_comments lint.
        comment("// ", "assets/images/acp/")
        + "\n\nconst Map<String, String> kAcpIconByKey = {\n"
        + body
        + "\n};\n\n"
        + "/// Asset path of the mark for [key], or null when there is none.\n"
        + "String? acpIconAsset(String? key) {\n"
        + "  if (key == null) return null;\n"
        + "  final icon = kAcpIconByKey[key.trim().toLowerCase()];\n"
        + "  return icon == null ? null : 'assets/images/acp/$icon.svg';\n"
        + "}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if a file is stale")
    args = parser.parse_args()

    index = build_index()
    outputs = {WEB_OUT: render_ts(index), MOBILE_OUT: render_dart(index)}

    stale = [p for p, text in outputs.items() if not p.exists() or p.read_text() != text]
    if args.check:
        for path in stale:
            print(f"stale: {path.relative_to(REPO)}", file=sys.stderr)
        if stale:
            print("run: python backend/scripts/gen_acp_icons.py", file=sys.stderr)
            return 1
        print(f"acp icon index up to date ({len(index)} keys)")
        return 0

    for path, text in outputs.items():
        path.write_text(text)
    print(f"wrote {len(index)} keys to {WEB_OUT.name} and {MOBILE_OUT.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
