"""Add DELETED status to AgentStatus enum

Revision ID: 2e2f1b18e835
Revises: f903f2e200c9
Create Date: 2025-08-10 16:31:11.910336

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "2e2f1b18e835"
down_revision: Union[str, None] = "f903f2e200c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add DELETED to the AgentStatus enum type
    op.execute("ALTER TYPE agentstatus ADD VALUE IF NOT EXISTS 'DELETED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: PostgreSQL doesn't support removing enum values easily
    # This would require recreating the entire enum type and all dependent columns
    # For safety, we'll just pass and handle this manually if needed
    pass
    # ### end Alembic commands ###
