"""Add git_diff field to agent_instances

Revision ID: 4e77ec2a7faa
Revises: 84cd4a8c9a18
Create Date: 2025-07-21 12:44:28.861822

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e77ec2a7faa"
down_revision: Union[str, None] = "84cd4a8c9a18"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent_instances", sa.Column("git_diff", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_instances", "git_diff")
    # ### end Alembic commands ###
