"""add instance metadata to agent instances

Revision ID: 8f18d049395f
Revises: 23aa590c6a55
Create Date: 2025-09-26 16:14:23.760077

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f18d049395f"
down_revision: Union[str, None] = "23aa590c6a55"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_instances",
        sa.Column("instance_metadata", sa.JSON(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_instances", "instance_metadata")
    # ### end Alembic commands ###
