"""Add name field to agent_instances

Revision ID: f092b4fd6d89
Revises: 40d4252deb5b
Create Date: 2025-08-06 17:09:41.579517

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f092b4fd6d89"
down_revision: Union[str, None] = "40d4252deb5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_instances", sa.Column("name", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_instances", "name")
    # ### end Alembic commands ###
