/**
 * Generated by backend/scripts/gen_acp_icons.py — do not edit by hand.
 *
 * Maps a provider id, or the display name a running session carries, to its
 * brand mark under public/images/acp/. A key that is absent has no mark; the caller
 * draws the generated initial-square rather than nothing.
 */

const ACP_ICON_BY_KEY: Record<string, string> = {
  'agoragentic': 'agoragentic-acp',
  'agoragentic-acp': 'agoragentic-acp',
  'amp': 'amp-acp',
  'amp-acp': 'amp-acp',
  'auggie': 'auggie',
  'auggie cli': 'auggie',
  'auggie-cli': 'auggie',
  'autohand': 'autohand',
  'autohand code': 'autohand',
  'autohand-code': 'autohand',
  'cline': 'cline',
  'codebuddy code': 'codebuddy-code',
  'codebuddy-code': 'codebuddy-code',
  'codewhale': 'codewhale',
  'cortex code': 'cortex-code',
  'cortex-code': 'cortex-code',
  'corust agent': 'corust-agent',
  'corust-agent': 'corust-agent',
  'crow-cli': 'crow-cli',
  'deepagents': 'deepagents',
  'dimcode': 'dimcode',
  'dirac': 'dirac',
  'factory droid': 'factory-droid',
  'factory-droid': 'factory-droid',
  'fast-agent': 'fast-agent',
  'glm agent': 'glm-acp-agent',
  'glm-acp-agent': 'glm-acp-agent',
  'glm-agent': 'glm-acp-agent',
  'goose': 'goose',
  'junie': 'junie',
  'kilo': 'kilo',
  'minion code': 'minion-code',
  'minion-code': 'minion-code',
  'mistral vibe': 'mistral-vibe',
  'mistral-vibe': 'mistral-vibe',
  'nova': 'nova',
  'poolside': 'poolside',
  'qoder': 'qoder',
  'qoder cli': 'qoder',
  'qoder-cli': 'qoder',
  'qwen code': 'qwen-code',
  'qwen-code': 'qwen-code',
  'sigit': 'sigit',
  'sigit code': 'sigit',
  'sigit-code': 'sigit',
  'stakpak': 'stakpak',
  'vt code': 'vtcode',
  'vt-code': 'vtcode',
  'vtcode': 'vtcode',
};

/** Public path of the mark for `key`, or null when there is none. */
export function acpIconSrc(key: string | null | undefined): string | null {
  if (!key) return null;
  const icon = ACP_ICON_BY_KEY[key.trim().toLowerCase()];
  return icon ? `/images/acp/${icon}.svg` : null;
}

/** Every lookup key that resolves to a mark. Exported for tests. */
export const ACP_ICON_KEYS = Object.keys(ACP_ICON_BY_KEY);
