from .enums import AgentStatus, SenderType, InstanceAccessLevel, TeamRole
from .models import (
    AgentInstance,
    APIKey,
    Base,
    Message,
    MessageAttachment,
    Machine,
    MachineAgentModels,
    MachineSpawnRequest,
    PushToken,
    SlashCommands,
    FileMentions,
    User,
    AgentType,
    UserInstanceAccess,
    Team,
    TeamMembership,
    TeamInstanceAccess,
)
from .task_models import (
    Project,
    ProjectDirectory,
    Task,
    TaskActivity,
    TaskComment,
    TaskLabel,
    TaskReaction,
    TaskSubscriber,
    ACTIVITY_ACTIONS,
    ACTIVITY_ACTOR_TYPES,
    COMMENT_AUTHOR_TYPES,
    COMMENT_KINDS,
    REACTION_TARGET_TYPES,
    SUBSCRIBER_REASONS,
    TASK_PRIORITIES,
    TASK_STATUSES,
)
from .automation_models import (
    Automation,
    AutomationRun,
    AUTOMATION_RUN_STATUSES,
    AUTOMATION_SCHEDULE_KINDS,
)
from .auth_models import (
    AuthEmailCode,
    UserCredential,
    EMAIL_CODE_PURPOSES,
)
from .activation_models import (
    ActivationNudge,
    ACTIVATION_NUDGE_CHANNELS,
    ACTIVATION_NUDGE_STATUSES,
)
from .actor import Actor, session_actor, set_session_actor
from .tasks import INBOX_PROJECT_NAME, get_or_create_inbox

# Side-effect import: registers the after_flush listener that generates
# `task_activity`. Importing the package is what turns task history on.
from . import task_activity as _task_activity  # noqa: F401
from .users import ensure_local_user

__all__ = [
    "Base",
    "User",
    "ensure_local_user",
    "AgentType",
    "AgentInstance",
    "AgentStatus",
    "APIKey",
    "Message",
    "MessageAttachment",
    "Machine",
    "MachineAgentModels",
    "MachineSpawnRequest",
    "UserInstanceAccess",
    "PushToken",
    "SenderType",
    "InstanceAccessLevel",
    "SlashCommands",
    "FileMentions",
    "Project",
    "ProjectDirectory",
    "Task",
    "TaskActivity",
    "TaskComment",
    "TaskLabel",
    "TaskReaction",
    "TaskSubscriber",
    "ACTIVITY_ACTIONS",
    "ACTIVITY_ACTOR_TYPES",
    "COMMENT_AUTHOR_TYPES",
    "COMMENT_KINDS",
    "REACTION_TARGET_TYPES",
    "SUBSCRIBER_REASONS",
    "TASK_PRIORITIES",
    "TASK_STATUSES",
    "INBOX_PROJECT_NAME",
    "get_or_create_inbox",
    "Actor",
    "session_actor",
    "set_session_actor",
    "Automation",
    "AutomationRun",
    "AUTOMATION_RUN_STATUSES",
    "AUTOMATION_SCHEDULE_KINDS",
    "UserCredential",
    "AuthEmailCode",
    "EMAIL_CODE_PURPOSES",
    "ActivationNudge",
    "ACTIVATION_NUDGE_CHANNELS",
    "ACTIVATION_NUDGE_STATUSES",
    "Team",
    "TeamMembership",
    "TeamRole",
    "TeamInstanceAccess",
]
