// Generated by backend/scripts/gen_acp_icons.py — do not edit by hand.
//
// Maps a provider id, or the display name a running session carries, to its
// brand mark under assets/images/acp/. A key that is absent has no mark; the caller
// draws the generated initial-square rather than nothing.

const Map<String, String> kAcpIconByKey = {
  'agoragentic': 'agoragentic-acp',
  'agoragentic-acp': 'agoragentic-acp',
  'amp': 'amp-acp',
  'amp-acp': 'amp-acp',
  'auggie': 'auggie',
  'auggie cli': 'auggie',
  'auggie-cli': 'auggie',
  'autohand': 'autohand',
  'autohand code': 'autohand',
  'autohand-code': 'autohand',
  'cline': 'cline',
  'codebuddy code': 'codebuddy-code',
  'codebuddy-code': 'codebuddy-code',
  'codewhale': 'codewhale',
  'cortex code': 'cortex-code',
  'cortex-code': 'cortex-code',
  'corust agent': 'corust-agent',
  'corust-agent': 'corust-agent',
  'crow-cli': 'crow-cli',
  'deepagents': 'deepagents',
  'devin': 'devin',
  'devin cli': 'devin',
  'devin-cli': 'devin',
  'dimcode': 'dimcode',
  'dirac': 'dirac',
  'factory droid': 'factory-droid',
  'factory-droid': 'factory-droid',
  'fast-agent': 'fast-agent',
  'glm agent': 'glm-acp-agent',
  'glm-acp-agent': 'glm-acp-agent',
  'glm-agent': 'glm-acp-agent',
  'goose': 'goose',
  'grok': 'grok',
  'junie': 'junie',
  'kilo': 'kilo',
  'kiro': 'kiro',
  'kiro cli': 'kiro',
  'kiro-cli': 'kiro',
  'minimax code': 'minimax-code',
  'minimax-code': 'minimax-code',
  'minion code': 'minion-code',
  'minion-code': 'minion-code',
  'mistral vibe': 'mistral-vibe',
  'mistral-vibe': 'mistral-vibe',
  'nova': 'nova',
  'poolside': 'poolside',
  'qoder': 'qoder',
  'qoder cli': 'qoder',
  'qoder-cli': 'qoder',
  'qwen code': 'qwen-code',
  'qwen-code': 'qwen-code',
  'sigit': 'sigit',
  'sigit code': 'sigit',
  'sigit-code': 'sigit',
  'stakpak': 'stakpak',
  'trae cli': 'traecli',
  'trae-cli': 'traecli',
  'traecli': 'traecli',
  'vt code': 'vtcode',
  'vt-code': 'vtcode',
  'vtcode': 'vtcode',
};

/// Asset path of the mark for [key], or null when there is none.
String? acpIconAsset(String? key) {
  if (key == null) return null;
  final icon = kAcpIconByKey[key.trim().toLowerCase()];
  return icon == null ? null : 'assets/images/acp/$icon.svg';
}
